dist: bionic
language: php
php:
  - 7.4
services:
  - mysql
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE testing;'
  - mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'homestead';"
  - mysql -u root -e "GRANT ALL ON testing.* TO 'homestead'@'localhost';"
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/bin/phpunit
